services:
  posts:
    build:
      context: ./posts
      dockerfile: Dockerfile
    ports:
      - "8901:8080"
    environment:
      - PORT=8080

  users:
    build:
      context: ./users
      dockerfile: Dockerfile
    ports:
      - "8902:8080"
    environment:
      - PORT=8080
