// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewProduct struct {
	Upc    string `json:"upc"`
	Name   string `json:"name"`
	Price  *int32 `json:"price,omitempty"`
	Weight *int32 `json:"weight,omitempty"`
}

type Product struct {
	Upc    string `json:"upc"`
	Name   string `json:"name"`
	Price  *int32 `json:"price,omitempty"`
	Weight *int32 `json:"weight,omitempty"`
}

func (Product) IsEntity() {}

type Query struct {
}
