package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/n9te9/go-graphql-federation-gateway/_example/ec/users/graph/model"
)

// FindUserByID is the resolver for the findUserByID field.
func (r *entityResolver) FindUserByID(ctx context.Context, id string) (*model.User, error) {
	return &model.User{ID: id, Username: "User " + id, Email: id + "@example.com"}, nil
}

// FindUserByUsername is the resolver for the findUserByUsername field.
func (r *entityResolver) FindUserByUsername(ctx context.Context, username string) (*model.User, error) {
	return &model.User{ID: "user_id_for_" + username, Username: username, Email: username + "@example.com"}, nil
}

// FindUserByEmail is the resolver for the findUserByEmail field.
func (r *entityResolver) FindUserByEmail(ctx context.Context, email string) (*model.User, error) {
	username := "user_for_" + email
	return &model.User{ID: "user_id_" + email, Username: username, Email: email}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
