package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/n9te9/go-graphql-federation-gateway/_example/ec/users/graph/model"
)

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	return &model.User{ID: "1", Username: "me", Email: "me@example.com",
		Profile: &model.Profile{DisplayName: "Display me", AvatarURL: "https://avatar.example.com/me"}}, nil
}

// UserByID is the resolver for the userById field.
func (r *queryResolver) UserByID(ctx context.Context, id string) (*model.User, error) {
	return &model.User{ID: id, Username: "user_" + id, Email: id + "@example.com",
		Profile: &model.Profile{DisplayName: "Display " + id, AvatarURL: "https://avatar.example.com/" + id}}, nil
}

// UserByUsername is the resolver for the userByUsername field.
func (r *queryResolver) UserByUsername(ctx context.Context, username string) (*model.User, error) {
	return &model.User{ID: "user_id_for_" + username, Username: username, Email: username + "@example.com",
		Profile: &model.Profile{DisplayName: "Display " + username, AvatarURL: "https://avatar.example.com/" + username}}, nil
}

// UserByEmail is the resolver for the userByEmail field.
func (r *queryResolver) UserByEmail(ctx context.Context, email string) (*model.User, error) {
	username := "user_for_" + email
	return &model.User{ID: "user_id_" + email, Username: username, Email: email,
		Profile: &model.Profile{DisplayName: "Display " + email, AvatarURL: "https://avatar.example.com/" + email}}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
