package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/go-graphql-federation-gateway/_example/ec/shipping/graph/model"
)

// ShippingEstimate is the resolver for the shippingEstimate field.
func (r *productResolver) ShippingEstimate(ctx context.Context, obj *model.Product) (*int32, error) {
	estimateRule := func(weight, price *int32) *int32 {
		if weight == nil || price == nil {
			return &[]int32{0}[0]
		}

		return &[]int32{int32(float64(*price) * 0.1)}[0]
	}

	return estimateRule(obj.Weight, obj.Price), nil
}

// Shipping is the resolver for the shipping field.
func (r *queryResolver) Shipping(ctx context.Context) (*string, error) {
	panic(fmt.Errorf("not implemented: Shipping - shipping"))
}

// Product returns ProductResolver implementation.
func (r *Resolver) Product() ProductResolver { return &productResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type productResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
