package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/n9te9/go-graphql-federation-gateway/_example/saas/events/graph/model"
)

// OrganizationEvents is the resolver for the organizationEvents field.
func (r *queryResolver) OrganizationEvents(ctx context.Context, orgID string) ([]model.BillingEvent, error) {
	// Return mixed billing events
	events := []model.BillingEvent{
		&model.Invoice{
			ID:      "inv-001",
			Amount:  6000.0,
			DueDate: "2024-03-01",
		},
		&model.PaymentReceived{
			ID:        "pay-001",
			Amount:    6000.0,
			Timestamp: "2024-02-15T10:00:00Z",
		},
		&model.SubscriptionChange{
			ID:        "sub-001",
			OldPlan:   "Enterprise",
			NewPlan:   "Enterprise Plus",
			Timestamp: "2024-02-01T09:00:00Z",
		},
	}
	return events, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
