// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Hotel struct {
	ID           string  `json:"id"`
	Name         string  `json:"name"`
	Location     string  `json:"location"`
	Price        float64 `json:"price"`
	Availability bool    `json:"availability"`
}

func (Hotel) IsEntity() {}

type Query struct {
}
