// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Bookable struct {
	ID           string  `json:"id"`
	Price        float64 `json:"price"`
	Availability bool    `json:"availability"`
}

func (Bookable) IsEntity() {}

type Query struct {
}
