// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
	GetID() string
}

type Product struct {
	ID      string    `json:"id"`
	Reviews []*Review `json:"reviews,omitempty"`
}

func (Product) IsEntity() {}

type Query struct {
}

type Review struct {
	ID         string   `json:"id"`
	Body       string   `json:"body"`
	AuthorName string   `json:"authorName"`
	Author     *User    `json:"author,omitempty"`
	Product    *Product `json:"product,omitempty"`
}

func (Review) IsNode()            {}
func (this Review) GetID() string { return this.ID }

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

func (User) IsEntity() {}
