// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Product struct {
	ID      string `json:"id"`
	InStock bool   `json:"inStock"`
}

func (Product) IsEntity() {}

type Query struct {
}
