// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Product struct {
	ID               string           `json:"id"`
	Weight           float64          `json:"weight"`
	ShippingAddress  *ShippingAddress `json:"shippingAddress"`
	InStock          bool             `json:"inStock"`
	ShippingCost     float64          `json:"shippingCost"`
	DeliveryEstimate string           `json:"deliveryEstimate"`
}

func (Product) IsEntity() {}

type Query struct {
}

type ShippingAddress struct {
	ZipCode string `json:"zipCode"`
	Country string `json:"country"`
}
