package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/n9te9/go-graphql-federation-gateway/_example/ec/products/graph/model"
)

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, name string, price int) (*model.Product, error) {
	// Generate a simple ID (in production, use UUID or database auto-increment)
	id := fmt.Sprintf("%d", len(name)+price)
	weight := 1.5 // Default weight
	internalCode := fmt.Sprintf("INTERNAL-%s", id)
	return &model.Product{ID: id, Name: name, Price: price, Weight: weight, InternalCode: internalCode}, nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id string) (*model.Product, error) {
	weight := 2.5 // Default weight for products
	internalCode := fmt.Sprintf("INTERNAL-%s", id)
	return &model.Product{ID: id, Name: "Product " + id, Price: 1000, Weight: weight, InternalCode: internalCode}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
