// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Organization struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	EmployeeCount int    `json:"employeeCount"`
}

func (Organization) IsEntity() {}

type Project struct {
	ID           string        `json:"id"`
	Name         string        `json:"name"`
	Organization *Organization `json:"organization"`
	Owner        string        `json:"owner"`
	CreatedAt    string        `json:"createdAt"`
}

func (Project) IsEntity() {}

type Query struct {
}

type Resource struct {
	ID string `json:"id"`
}

func (Resource) IsEntity() {}
