// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Organization struct {
	ID string `json:"id"`
}

func (Organization) IsEntity() {}

type Project struct {
	ID           string        `json:"id"`
	Name         string        `json:"name"`
	Organization *Organization `json:"organization"`
}

func (Project) IsEntity() {}

type Query struct {
}
