package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/n9te9/go-graphql-federation-gateway/_example/fintech/customers/graph/model"
)

// FindCustomerByID is the resolver for the findCustomerByID field.
func (r *entityResolver) FindCustomerByID(ctx context.Context, id string) (*model.Customer, error) {
	panic(fmt.Errorf("not implemented: FindCustomerByID - findCustomerByID"))
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
