// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Auditable struct {
	AuditID    string `json:"auditId"`
	CreatedAt  string `json:"createdAt"`
	ModifiedAt string `json:"modifiedAt"`
	ModifiedBy string `json:"modifiedBy"`
}

func (Auditable) IsEntity() {}

type Query struct {
}
