package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/n9te9/go-graphql-federation-gateway/_example/fintech/transactions/graph/model"
)

// FindAccountByID is the resolver for the findAccountByID field.
func (r *entityResolver) FindAccountByID(ctx context.Context, id string) (*model.Account, error) {
	return &model.Account{
		ID: id,
		Transactions: []*model.Transaction{
			{ID: "tx_101", Amount: 500},
			{ID: "tx_102", Amount: -200},
		},
	}, nil
}

// FindTransactionByID is the resolver for the findTransactionByID field.
func (r *entityResolver) FindTransactionByID(ctx context.Context, id string) (*model.Transaction, error) {
	return &model.Transaction{
		ID:     id,
		Amount: 100,
	}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
