package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/n9te9/go-graphql-federation-gateway/_example/fintech/transactions/graph/model"
)

// FindAccountByIban is the resolver for the findAccountByIban field.
func (r *entityResolver) FindAccountByIban(ctx context.Context, iban string) (*model.Account, error) {
	// Calculate risk score based on balance (provided via @requires)
	// For testing, use a simple formula: riskScore = balance / 100
	balance := 1000 // This will be provided by the gateway via @requires
	riskScore := float64(balance) / 100.0

	return &model.Account{
		Iban:      iban,
		RiskScore: riskScore,
		Transactions: []*model.Transaction{
			{ID: "tx_1", Amount: 100},
		},
	}, nil
}

// FindTransactionByID is the resolver for the findTransactionByID field.
func (r *entityResolver) FindTransactionByID(ctx context.Context, id string) (*model.Transaction, error) {
	return &model.Transaction{
		ID:     id,
		Amount: 100,
	}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
