package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"

	"github.com/n9te9/go-graphql-federation-gateway/_example/social/feed/graph/model"
)

// FindContentByID is the resolver for the findContentByID field.
func (r *entityResolver) FindContentByID(ctx context.Context, id string) (*model.Content, error) {
	panic(fmt.Errorf("not implemented: FindContentByID - findContentByID"))
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
