package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"
	"time"

	"github.com/n9te9/go-graphql-federation-gateway/_example/social/feed/graph/model"
)

// Feed is the resolver for the feed field.
func (r *queryResolver) Feed(ctx context.Context, userID string) ([]*model.Content, error) {
	now := time.Now()
	return []*model.Content{
		{
			ID:        "content1",
			Body:      "Hello from the feed! This is the first post.",
			Author:    &model.User{ID: "user1"},
			CreatedAt: now.Add(-2 * time.Hour).Format(time.RFC3339),
		},
		{
			ID:        "content2",
			Body:      "GraphQL Federation is amazing!",
			Author:    &model.User{ID: "user2"},
			CreatedAt: now.Add(-1 * time.Hour).Format(time.RFC3339),
		},
		{
			ID:        "content3",
			Body:      fmt.Sprintf("Latest content for user %s", userID),
			Author:    &model.User{ID: userID},
			CreatedAt: now.Add(-30 * time.Minute).Format(time.RFC3339),
		},
	}, nil
}

// Content is the resolver for the content field.
func (r *queryResolver) Content(ctx context.Context, id string) (*model.Content, error) {
	now := time.Now()
	return &model.Content{
		ID:        id,
		Body:      fmt.Sprintf("Content body for %s", id),
		Author:    &model.User{ID: "user1"},
		CreatedAt: now.Format(time.RFC3339),
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
