package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/n9te9/go-graphql-federation-gateway/_example/social/users/graph/model"
)

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	if id == "user1" {
		return &model.User{ID: id, Name: "Alice", Email: "alice@example.com"}, nil
	}
	if id == "user2" {
		return &model.User{ID: id, Name: "Bob", Email: "bob@example.com"}, nil
	}
	return &model.User{ID: id, Name: "User " + id, Email: id + "@example.com"}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *queryResolver) Search(ctx context.Context, query string) ([]model.SearchResult, error) {
	// Return a mix of Users and Posts for demonstration
	results := []model.SearchResult{
		&model.User{ID: "user1", Name: "Alice"},
		&model.Post{ID: "post1", UserID: "user1", Content: "Hello world!"},
		&model.User{ID: "user2", Name: "Bob"},
		&model.Post{ID: "post2", UserID: "user2", Content: "GraphQL is awesome!"},
	}
	return results, nil
}
*/
