package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"strings"

	"github.com/n9te9/go-graphql-federation-gateway/_example/ec/search/graph/model"
)

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, query string) ([]model.SearchResult, error) {
	results := []model.SearchResult{}
	q := strings.ToLower(query)
	// "all" is a special case that returns all result types for testing
	if q == "all" {
		results = append(results, &model.Product{ID: "p1", Name: "Product p1"})
		results = append(results, &model.User{ID: "user1", Username: "Alice"})
		return results, nil
	}
	// Search products
	if strings.Contains(q, "product") || strings.Contains(q, "p") {
		results = append(results, &model.Product{ID: "p1", Name: "Product p1"})
	}
	// Search users
	if strings.Contains(q, "user") || strings.Contains(q, "alice") {
		results = append(results, &model.User{ID: "user1", Username: "Alice"})
	}
	// Search reviews
	if strings.Contains(q, "review") {
		results = append(results, &model.Review{ID: "r1"})
	}
	return results, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
