package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/n9te9/go-graphql-federation-gateway/_example/travel/pricing/graph/model"
)

// FindFlightByNumberAndDepartureDate is the resolver for the findFlightByNumberAndDepartureDate field.
func (r *entityResolver) FindFlightByNumberAndDepartureDate(ctx context.Context, number string, departureDate string) (*model.Flight, error) {
	// Return dynamic price with priceType and discount
	price := 450.0
	priceType := "early-bird"
	discount := 50.0

	return &model.Flight{
		Number:        number,
		DepartureDate: departureDate,
		Price:         price,
		PriceType:     priceType,
		Discount:      &discount,
	}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
