// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
	GetID() string
}

type Profile struct {
	DisplayName string `json:"displayName"`
	AvatarURL   string `json:"avatarUrl"`
}

type Query struct {
}

type User struct {
	ID       string   `json:"id"`
	Username string   `json:"username"`
	Email    string   `json:"email"`
	Profile  *Profile `json:"profile"`
}

func (User) IsNode()            {}
func (this User) GetID() string { return this.ID }

func (User) IsEntity() {}
