// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type FinancialActivity interface {
	IsFinancialActivity()
}

type AccountOpening struct {
	ID          string `json:"id"`
	CustomerID  string `json:"customerId"`
	Timestamp   string `json:"timestamp"`
	AccountType string `json:"accountType"`
}

func (AccountOpening) IsFinancialActivity() {}

type Query struct {
}

type TierUpgrade struct {
	ID         string `json:"id"`
	CustomerID string `json:"customerId"`
	OldTier    string `json:"oldTier"`
	NewTier    string `json:"newTier"`
	Timestamp  string `json:"timestamp"`
}

func (TierUpgrade) IsFinancialActivity() {}

type Transaction struct {
	ID string `json:"id"`
}

func (Transaction) IsFinancialActivity() {}

func (Transaction) IsEntity() {}
