package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/n9te9/go-graphql-federation-gateway/_example/travel/search/graph/model"
)

// SearchTravel is the resolver for the searchTravel field.
func (r *queryResolver) SearchTravel(ctx context.Context, from string, to string) ([]model.TravelOption, error) {
	// Return mixed Flight and Hotel results
	results := []model.TravelOption{
		&model.Flight{
			Number:        "AA100",
			DepartureDate: "2026-03-01",
		},
		&model.Hotel{
			ID: "h1",
		},
		&model.Flight{
			Number:        "BA200",
			DepartureDate: "2026-03-02",
		},
		&model.Hotel{
			ID: "h2",
		},
	}
	return results, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
