// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BillingEvent interface {
	IsBillingEvent()
}

type Invoice struct {
	ID      string  `json:"id"`
	Amount  float64 `json:"amount"`
	DueDate string  `json:"dueDate"`
}

func (Invoice) IsBillingEvent() {}

type PaymentReceived struct {
	ID        string  `json:"id"`
	Amount    float64 `json:"amount"`
	Timestamp string  `json:"timestamp"`
}

func (PaymentReceived) IsBillingEvent() {}

type Query struct {
}

type SubscriptionChange struct {
	ID        string `json:"id"`
	OldPlan   string `json:"oldPlan"`
	NewPlan   string `json:"newPlan"`
	Timestamp string `json:"timestamp"`
}

func (SubscriptionChange) IsBillingEvent() {}
