// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Content struct {
	ID        string `json:"id"`
	Body      string `json:"body"`
	Author    *User  `json:"author"`
	CreatedAt string `json:"createdAt"`
}

func (Content) IsEntity() {}

type Query struct {
}

type User struct {
	ID string `json:"id"`
}

func (User) IsEntity() {}
