// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type SearchResult interface {
	IsSearchResult()
}

type Product struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (Product) IsSearchResult() {}

func (Product) IsEntity() {}

type Query struct {
}

type Review struct {
	ID string `json:"id"`
}

func (Review) IsSearchResult() {}

func (Review) IsEntity() {}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
}

func (User) IsSearchResult() {}

func (User) IsEntity() {}
