package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/n9te9/go-graphql-federation-gateway/_example/saas/organizations/graph/model"
)

// Organization is the resolver for the organization field.
func (r *queryResolver) Organization(ctx context.Context, id string) (*model.Organization, error) {
	// Return test data for org1
	if id == "org1" {
		return &model.Organization{
			ID:            id,
			Name:          "Acme Corp",
			EmployeeCount: 50,
		}, nil
	}
	return &model.Organization{
		ID:            id,
		Name:          "Org " + id,
		EmployeeCount: 10,
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
