// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID               string `json:"id"`
	Body             string `json:"body"`
	ModerationStatus string `json:"moderationStatus"`
}

func (Comment) IsEntity() {}

type Post struct {
	ID               string `json:"id"`
	Content          string `json:"content"`
	ModerationStatus string `json:"moderationStatus"`
}

func (Post) IsEntity() {}

type Query struct {
}
