// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Content struct {
	ID string `json:"id"`
}

func (Content) IsEntity() {}

type Post struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	Body      string `json:"body"`
	LikeCount int    `json:"likeCount"`
	Author    *User  `json:"author"`
	CreatedAt string `json:"createdAt"`
}

func (Post) IsEntity() {}

type Query struct {
}

type User struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Posts []*Post `json:"posts"`
}

func (User) IsEntity() {}
