// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Post struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
	Author  *User  `json:"author"`
}

func (Post) IsEntity() {}

type Query struct {
}

type User struct {
	ID    string  `json:"id"`
	Posts []*Post `json:"posts"`
}

func (User) IsEntity() {}
