// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Account struct {
	Iban     string    `json:"iban"`
	ID       string    `json:"id"`
	Balance  int       `json:"balance"`
	Customer *Customer `json:"customer"`
}

func (Account) IsEntity() {}

type Customer struct {
	ID       string     `json:"id"`
	Tier     string     `json:"tier"`
	Accounts []*Account `json:"accounts"`
}

func (Customer) IsEntity() {}

type Query struct {
}
