package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/n9te9/go-graphql-federation-gateway/_example/saas/billing-v2/graph/model"
)

// FindOrganizationByID is the resolver for the findOrganizationByID field.
func (r *entityResolver) FindOrganizationByID(ctx context.Context, id string) (*model.Organization, error) {
	// Return billing info with overridden values
	monthlyCost := 6000.0
	return &model.Organization{
		ID:          id,
		MonthlyCost: monthlyCost,
		Billing: &model.BillingInfo{
			ID:   "billing-" + id,
			Plan: "Enterprise Plus",
			Features: []string{
				"Advanced Analytics",
				"24/7 Support",
			},
		},
	}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
