package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/n9te9/go-graphql-federation-gateway/_example/saas/projects/graph/model"
)

// FindOrganizationByID is the resolver for the findOrganizationByID field.
func (r *entityResolver) FindOrganizationByID(ctx context.Context, id string) (*model.Organization, error) {
	return &model.Organization{ID: id}, nil
}

// FindProjectByID is the resolver for the findProjectByID field.
func (r *entityResolver) FindProjectByID(ctx context.Context, id string) (*model.Project, error) {
	if id == "proj1" {
		return &model.Project{
			ID:           id,
			Name:         "Project Alpha",
			Organization: &model.Organization{ID: "org1"},
		}, nil
	}
	return &model.Project{
		ID:           id,
		Name:         "Project " + id,
		Organization: &model.Organization{ID: "unknown"},
	}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
