package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/n9te9/go-graphql-federation-gateway/_example/saas/projects/graph/model"
)

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, id string) (*model.Project, error) {
	if id == "proj1" {
		return &model.Project{
			ID:           id,
			Name:         "Project Alpha",
			Organization: &model.Organization{ID: "org1"},
		}, nil
	}
	return &model.Project{
		ID:           id,
		Name:         "Project " + id,
		Organization: &model.Organization{ID: "unknown"},
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
