package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"time"

	"github.com/n9te9/go-graphql-federation-gateway/_example/social/notifications/graph/model"
)

// Notifications is the resolver for the notifications field.
func (r *queryResolver) Notifications(ctx context.Context, userID string) ([]model.Notification, error) {
	now := time.Now()
	return []model.Notification{
		&model.LikeNotification{
			ID:        "like1",
			Post:      &model.Post{ID: "post1"},
			LikedBy:   &model.User{ID: "user2"},
			Timestamp: now.Add(-3 * time.Hour).Format(time.RFC3339),
		},
		&model.CommentNotification{
			ID:        "comment1",
			Comment:   &model.Comment{ID: "comment1"},
			Timestamp: now.Add(-2 * time.Hour).Format(time.RFC3339),
		},
		&model.MentionNotification{
			ID:          "mention1",
			Post:        &model.Post{ID: "post2"},
			MentionedBy: &model.User{ID: "user1"},
			Timestamp:   now.Add(-1 * time.Hour).Format(time.RFC3339),
		},
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
