// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Flight struct {
	Number        string   `json:"number"`
	DepartureDate string   `json:"departureDate"`
	Price         float64  `json:"price"`
	PriceType     string   `json:"priceType"`
	Discount      *float64 `json:"discount,omitempty"`
}

func (Flight) IsEntity() {}

type Query struct {
}
