package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/n9te9/go-graphql-federation-gateway/_example/travel/bookables/graph/model"
)

// FindBookableByID is the resolver for the findBookableByID field.
func (r *entityResolver) FindBookableByID(ctx context.Context, id string) (*model.Bookable, error) {
	// Return bookable data based on ID
	availability := true
	price := 500.0

	if id == "flight-aa100" {
		price = 500.0
		availability = true
	} else if id == "hotel-h1" {
		price = 200.0
		availability = true
	} else if id == "hotel-h2" {
		price = 350.0
		availability = false
	}

	return &model.Bookable{
		ID:           id,
		Price:        price,
		Availability: availability,
	}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
