package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/n9te9/go-graphql-federation-gateway/_example/travel/bookables/graph/model"
)

// SearchBookables is the resolver for the searchBookables field.
func (r *queryResolver) SearchBookables(ctx context.Context, from *string, to *string) ([]*model.Bookable, error) {
	// Return sample bookable results
	return []*model.Bookable{
		{
			ID:           "flight-aa100",
			Price:        500.0,
			Availability: true,
		},
		{
			ID:           "hotel-h1",
			Price:        200.0,
			Availability: true,
		},
		{
			ID:           "hotel-h2",
			Price:        350.0,
			Availability: false,
		},
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
