package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/n9te9/go-graphql-federation-gateway/_example/travel/hotels/graph/model"
)

// FindHotelByID is the resolver for the findHotelByID field.
func (r *entityResolver) FindHotelByID(ctx context.Context, id string) (*model.Hotel, error) {
	// Return hotel data based on ID with name, location, price, availability
	if id == "h1" {
		return &model.Hotel{
			ID:           id,
			Name:         "Grand Plaza Hotel",
			Location:     "New York",
			Price:        200.0,
			Availability: true,
		}, nil
	}
	return &model.Hotel{
		ID:           id,
		Name:         "Sunset Resort",
		Location:     "Los Angeles",
		Price:        350.0,
		Availability: false,
	}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
