services:
  # gateway:
  #   build:
  #     context: . 
  #     dockerfile: ../Dockerfile
  #   ports:
  #     - "9001:9000"
  customers:
    build: { context: ./customers, dockerfile: Dockerfile }
    ports: ["8201:8080"]
  accounts:
    build: { context: ./accounts, dockerfile: Dockerfile }
    ports: ["8202:8080"]
  transactions:
    build: { context: ./transactions, dockerfile: Dockerfile }
    ports: ["8203:8080"]
  audit:
    build:
      context: ./audit
      dockerfile: Dockerfile
    ports:
      - "8204:8080"
    environment:
      - PORT=8080
  customers-eu:
    build:
      context: ./customers-eu
      dockerfile: Dockerfile
    ports:
      - "8205:8080"
    environment:
      - PORT=8080
  activities:
    build:
      context: ./activities
      dockerfile: Dockerfile
    ports:
      - "8206:8080"
    environment:
      - PORT=8080
