// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID        string `json:"id"`
	Body      string `json:"body"`
	Author    *User  `json:"author"`
	CreatedAt string `json:"createdAt"`
}

func (Comment) IsEntity() {}

type Content struct {
	ID string `json:"id"`
}

func (Content) IsEntity() {}

type Post struct {
	ID              string     `json:"id"`
	LikeCount       int        `json:"likeCount"`
	Comments        []*Comment `json:"comments"`
	EngagementScore float64    `json:"engagementScore"`
}

func (Post) IsEntity() {}

type Query struct {
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (User) IsEntity() {}
