// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID     string `json:"id"`
	Body   string `json:"body"`
	Author *User  `json:"author"`
}

func (Comment) IsEntity() {}

type Post struct {
	ID       string     `json:"id"`
	Comments []*Comment `json:"comments"`
}

func (Post) IsEntity() {}

type Query struct {
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (User) IsEntity() {}
