// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BillingInfo struct {
	ID   string `json:"id"`
	Plan string `json:"plan"`
}

func (BillingInfo) IsEntity() {}

type Organization struct {
	ID      string       `json:"id"`
	Billing *BillingInfo `json:"billing,omitempty"`
}

func (Organization) IsEntity() {}

type Query struct {
}
