// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BillingInfo struct {
	ID   string `json:"id"`
	Plan string `json:"plan"`
}

func (BillingInfo) IsEntity() {}

type Organization struct {
	ID            string       `json:"id"`
	EmployeeCount int          `json:"employeeCount"`
	Billing       *BillingInfo `json:"billing,omitempty"`
	MonthlyCost   float64      `json:"monthlyCost"`
}

func (Organization) IsEntity() {}

type Query struct {
}
