package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/n9te9/go-graphql-federation-gateway/_example/ec/inventory/graph/model"
)

// FindProductByID is the resolver for the findProductByID field.
func (r *entityResolver) FindProductByID(ctx context.Context, id string) (*model.Product, error) {
	inStock := false
	// Calculate shipping cost based on weight (if provided via @requires)
	// Weight should be available in the representation
	// For now, return a fixed value - actual implementation would use weight
	shippingCost := 5.0

	return &model.Product{
		ID:           id,
		InStock:      inStock,
		ShippingCost: shippingCost,
	}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
