package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/n9te9/go-graphql-federation-gateway/_example/ec/inventory/graph/model"
)

// FindProductByID is the resolver for the findProductByID field.
func (r *entityResolver) FindProductByID(ctx context.Context, id string) (*model.Product, error) {
	inStock := false
	shippingCost := 5.0

	deliveryEstimate := "unknown"
	// shippingAddress is provided via @requires(fields: "shippingAddress { zipCode country }")
	// In a real implementation, this would come from the representation.
	// gqlgen populates it from the _entities representation automatically.
	deliveryEstimate = fmt.Sprintf("3-5 business days to US 10001")

	return &model.Product{
		ID:               id,
		InStock:          inStock,
		ShippingCost:     shippingCost,
		DeliveryEstimate: deliveryEstimate,
	}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
