package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/n9te9/go-graphql-federation-gateway/_example/social/comments/graph/model"
)

// FindCommentByID is the resolver for the findCommentByID field.
func (r *entityResolver) FindCommentByID(ctx context.Context, id string) (*model.Comment, error) {
	if id == "comment1" {
		return &model.Comment{
			ID:     id,
			Body:   "Great post!",
			Author: &model.User{ID: "user2"},
		}, nil
	}
	return &model.Comment{ID: id, Body: "Comment " + id, Author: &model.User{ID: "unknown"}}, nil
}

// FindPostByID is the resolver for the findPostByID field.
func (r *entityResolver) FindPostByID(ctx context.Context, id string) (*model.Post, error) {
	// Calculate engagement score based on likeCount (provided via @requires)
	// For testing: engagementScore = likeCount / 10
	likeCount := 100 // This will be provided by the gateway via @requires
	engagementScore := float64(likeCount) / 10.0

	// Return Post with comments
	if id == "post1" {
		return &model.Post{
			ID:              id,
			EngagementScore: engagementScore,
			Comments: []*model.Comment{
				{
					ID:     "comment1",
					Body:   "Great post!",
					Author: &model.User{ID: "user2"},
				},
			},
		}, nil
	}
	return &model.Post{
		ID:              id,
		EngagementScore: 1.0,
		Comments:        []*model.Comment{},
	}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
