package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/n9te9/go-graphql-federation-gateway/_example/ec/review/graph/model"
)

// CreateReview is the resolver for the createReview field.
func (r *mutationResolver) CreateReview(ctx context.Context, review model.NewReview) (*model.Review, error) {
	newReview := &model.Review{
		ID:      fmt.Sprintf("%d", len(reviews)+1),
		Product: &model.Product{Upc: review.Product.Upc},
		Body:    review.Body,
		Author:  &model.User{ID: review.Author.ID},
	}

	for _, product := range products {
		if product.Upc == review.Product.Upc {
			product.Reviews = append(product.Reviews, newReview)
			break
		}
	}

	reviews[newReview.ID] = newReview

	return newReview, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
