package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/n9te9/go-graphql-federation-gateway/_example/social/posts/graph/model"
)

// FindPostByID is the resolver for the findPostByID field.
func (r *entityResolver) FindPostByID(ctx context.Context, id string) (*model.Post, error) {
	if id == "post1" {
		return &model.Post{
			ID:      id,
			Title:   "My First Post",
			Content: "This is my first post",
			Author:  &model.User{ID: "user1"},
		}, nil
	}
	return &model.Post{ID: id, Title: "Post " + id, Content: "Content " + id, Author: &model.User{ID: "unknown"}}, nil
}

// FindUserByID is the resolver for the findUserByID field.
func (r *entityResolver) FindUserByID(ctx context.Context, id string) (*model.User, error) {
	// Return User with posts
	if id == "user1" {
		return &model.User{
			ID: id,
			Posts: []*model.Post{
				{
					ID:      "post1",
					Title:   "My First Post",
					Content: "This is my first post",
					Author:  &model.User{ID: "user1"},
				},
			},
		}, nil
	}
	return &model.User{ID: id, Posts: []*model.Post{}}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
