package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/n9te9/go-graphql-federation-gateway/_example/social/posts/graph/model"
)

// FindContentByID is the resolver for the findContentByID field.
func (r *entityResolver) FindContentByID(ctx context.Context, id string) (*model.Content, error) {
	panic(fmt.Errorf("not implemented: FindContentByID - findContentByID"))
}

// FindPostByID is the resolver for the findPostByID field.
func (r *entityResolver) FindPostByID(ctx context.Context, id string) (*model.Post, error) {
	if id == "post1" {
		return &model.Post{
			ID:        id,
			Title:     "My First Post",
			Content:   "This is my first post",
			Body:      "This is my first post",
			LikeCount: 100,
			Author:    &model.User{ID: "user1"},
			CreatedAt: "2024-01-01T00:00:00Z",
		}, nil
	}
	return &model.Post{
		ID:        id,
		Title:     "Post " + id,
		Content:   "Content " + id,
		Body:      "Content " + id,
		LikeCount: 10,
		Author:    &model.User{ID: "unknown"},
		CreatedAt: "2024-01-01T00:00:00Z",
	}, nil
}

// FindUserByID is the resolver for the findUserByID field.
func (r *entityResolver) FindUserByID(ctx context.Context, id string) (*model.User, error) {
	// Return User with posts
	if id == "user1" {
		return &model.User{
			ID: id,
			Posts: []*model.Post{
				{
					ID:        "post1",
					Title:     "My First Post",
					Content:   "This is my first post",
					Body:      "This is my first post",
					LikeCount: 100,
					Author:    &model.User{ID: "user1"},
					CreatedAt: "2024-01-01T00:00:00Z",
				},
			},
		}, nil
	}
	return &model.User{ID: id, Posts: []*model.Post{}}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
