package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/n9te9/go-graphql-federation-gateway/_example/travel/bookings/graph/model"
)

// FindBookingByID is the resolver for the findBookingByID field.
func (r *entityResolver) FindBookingByID(ctx context.Context, id string) (*model.Booking, error) {
	return &model.Booking{ID: id, Flight: &model.Flight{Number: "NH101", DepartureDate: "2026-02-10"}}, nil
}

// FindFlightByNumberAndDepartureDate is the resolver for the findFlightByNumberAndDepartureDate field.
func (r *entityResolver) FindFlightByNumberAndDepartureDate(ctx context.Context, number string, departureDate string) (*model.Flight, error) {
	return &model.Flight{Number: number, DepartureDate: departureDate}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
