package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/n9te9/go-graphql-federation-gateway/_example/fintech/audit/graph/model"
)

// FindAuditableByAuditID is the resolver for the findAuditableByAuditID field.
func (r *entityResolver) FindAuditableByAuditID(ctx context.Context, auditID string) (*model.Auditable, error) {
	return &model.Auditable{
		AuditID:    auditID,
		CreatedAt:  "2024-01-01T12:00:00Z",
		ModifiedAt: "2024-01-15T14:30:00Z",
		ModifiedBy: "system-user",
	}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
