package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/n9te9/go-graphql-federation-gateway/_example/fintech/audit/graph/model"
)

// AuditLog is the resolver for the auditLog field.
func (r *queryResolver) AuditLog(ctx context.Context) ([]*model.Auditable, error) {
	return []*model.Auditable{
		{
			AuditID:    "audit-001",
			CreatedAt:  "2024-01-01T10:00:00Z",
			ModifiedAt: "2024-01-01T10:00:00Z",
			ModifiedBy: "admin",
		},
		{
			AuditID:    "audit-002",
			CreatedAt:  "2024-01-02T11:00:00Z",
			ModifiedAt: "2024-01-02T15:00:00Z",
			ModifiedBy: "system",
		},
	}, nil
}

// AuditEntry is the resolver for the auditEntry field.
func (r *queryResolver) AuditEntry(ctx context.Context, id string) (*model.Auditable, error) {
	return &model.Auditable{
		AuditID:    id,
		CreatedAt:  "2024-01-01T12:00:00Z",
		ModifiedAt: "2024-01-15T14:30:00Z",
		ModifiedBy: "user-" + id,
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
