// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Flight struct {
	Number        string  `json:"number"`
	DepartureDate string  `json:"departureDate"`
	Origin        string  `json:"origin"`
	Destination   string  `json:"destination"`
	Price         float64 `json:"price"`
}

func (Flight) IsEntity() {}

type Query struct {
}
