package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/n9te9/go-graphql-federation-gateway/_example/fintech/activities/graph/model"
)

// CustomerActivity is the resolver for the customerActivity field.
func (r *queryResolver) CustomerActivity(ctx context.Context, customerID string) ([]model.FinancialActivity, error) {
	return []model.FinancialActivity{
		&model.Transaction{
			ID: "txn-" + customerID + "-001",
		},
		&model.AccountOpening{
			ID:          "acc-" + customerID + "-001",
			CustomerID:  customerID,
			Timestamp:   "2024-01-05T10:00:00Z",
			AccountType: "Savings",
		},
		&model.TierUpgrade{
			ID:         "tier-" + customerID + "-001",
			CustomerID: customerID,
			OldTier:    "Standard",
			NewTier:    "Premium",
			Timestamp:  "2024-02-01T15:30:00Z",
		},
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
