package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/n9te9/federation-gateway/_example/ec/product/graph/model"
)

var products = map[string]*model.Product{
	"1": {
		Upc:   "1",
		Name:  "hogehoge",
		Price: &[]int32{1000}[0],
	},
	"2": {
		Upc:   "2",
		Name:  "fugafuga",
		Price: &[]int32{2000}[0],
	},
	"3": {
		Upc:   "3",
		Name:  "piyopiyo",
		Price: &[]int32{3000}[0],
	},
}

// TopProducts is the resolver for the topProducts field.
func (r *queryResolver) TopProducts(ctx context.Context, first *int32) ([]*model.Product, error) {
	var result []*model.Product
	count := int32(0)
	for _, p := range products {
		result = append(result, p)
		count++
		if first != nil && count >= *first {
			break
		}
	}

	return result, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
