package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/n9te9/go-graphql-federation-gateway/_example/travel/flights/graph/model"
)

// FindFlightByNumberAndDepartureDate is the resolver for the findFlightByNumberAndDepartureDate field.
func (r *entityResolver) FindFlightByNumberAndDepartureDate(ctx context.Context, number string, departureDate string) (*model.Flight, error) {
	if number == "AA100" && departureDate == "2026-03-01" {
		return &model.Flight{
			Number:        number,
			DepartureDate: departureDate,
			Origin:        "SFO",
			Destination:   "JFK",
		}, nil
	}
	return &model.Flight{Number: number, DepartureDate: departureDate, Origin: "HND", Destination: "NRT"}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
