package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/n9te9/go-graphql-federation-gateway/_example/travel/flights/graph/model"
)

// Flight is the resolver for the flight field.
func (r *queryResolver) Flight(ctx context.Context, number string, departureDate string) (*model.Flight, error) {
	panic(fmt.Errorf("not implemented: Flight - flight"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
