package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/n9te9/go-graphql-federation-gateway/_example/ec/catalog/graph/model"
)

// FindNodeByID is the resolver for the findNodeByID field.
func (r *entityResolver) FindNodeByID(ctx context.Context, id string) (*model.Node, error) {
	return &model.Node{ID: id}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
