// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Organization struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	EmployeeCount int    `json:"employeeCount"`
}

func (Organization) IsEntity() {}

type Query struct {
}
