// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Notification interface {
	IsNotification()
}

type Comment struct {
	ID string `json:"id"`
}

func (Comment) IsEntity() {}

type CommentNotification struct {
	ID        string   `json:"id"`
	Comment   *Comment `json:"comment"`
	Timestamp string   `json:"timestamp"`
}

func (CommentNotification) IsNotification() {}

type LikeNotification struct {
	ID        string `json:"id"`
	Post      *Post  `json:"post"`
	LikedBy   *User  `json:"likedBy"`
	Timestamp string `json:"timestamp"`
}

func (LikeNotification) IsNotification() {}

type MentionNotification struct {
	ID          string `json:"id"`
	Post        *Post  `json:"post"`
	MentionedBy *User  `json:"mentionedBy"`
	Timestamp   string `json:"timestamp"`
}

func (MentionNotification) IsNotification() {}

type Post struct {
	ID string `json:"id"`
}

func (Post) IsEntity() {}

type Query struct {
}

type User struct {
	ID string `json:"id"`
}

func (User) IsEntity() {}
