package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"

	"github.com/n9te9/go-graphql-federation-gateway/_example/social/moderation/graph/model"
)

// FindCommentByID is the resolver for the findCommentByID field.
func (r *entityResolver) FindCommentByID(ctx context.Context, id string) (*model.Comment, error) {
	return &model.Comment{
		ID:               id,
		Body:             fmt.Sprintf("Moderated comment body for %s", id),
		ModerationStatus: "approved",
	}, nil
}

// FindPostByID is the resolver for the findPostByID field.
func (r *entityResolver) FindPostByID(ctx context.Context, id string) (*model.Post, error) {
	return &model.Post{
		ID:               id,
		Content:          fmt.Sprintf("Moderated post content for %s", id),
		ModerationStatus: "approved",
	}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
