package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/n9te9/go-graphql-federation-gateway/_example/fintech/accounts/graph/model"
)

// FindAccountByIban is the resolver for the findAccountByIban field.
func (r *entityResolver) FindAccountByIban(ctx context.Context, iban string) (*model.Account, error) {
	return &model.Account{
		Iban:     iban,
		ID:       "acc_" + iban,
		Balance:  1000,
		Customer: &model.Customer{ID: "1"},
	}, nil
}

// FindCustomerByID is the resolver for the findCustomerByID field.
func (r *entityResolver) FindCustomerByID(ctx context.Context, id string) (*model.Customer, error) {
	return &model.Customer{
		ID: id,
		Accounts: []*model.Account{
			{Iban: "IBAN 1", ID: "acc_IBAN 1", Balance: 1000, Customer: &model.Customer{ID: id}},
		},
	}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *entityResolver) FindAccountByID(ctx context.Context, id string) (*model.Account, error) {
	return &model.Account{
		ID:       id,
		Balance:  1000,
		Customer: &model.Customer{ID: "customer_of_" + id},
	}, nil
}
*/
