package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/n9te9/go-graphql-federation-gateway/_example/fintech/accounts/graph/model"
)

// FindAccountByIban is the resolver for the findAccountByIban field.
func (r *entityResolver) FindAccountByIban(ctx context.Context, iban string) (*model.Account, error) {
	return &model.Account{
		Iban:     iban,
		ID:       "acc_" + iban,
		Balance:  1000,
		Customer: &model.Customer{ID: "1"},
	}, nil
}

// FindCustomerByID is the resolver for the findCustomerByID field.
func (r *entityResolver) FindCustomerByID(ctx context.Context, id string) (*model.Customer, error) {
	return &model.Customer{
		ID: id,
		Accounts: []*model.Account{
			{Iban: "IBAN 1", ID: "acc_IBAN 1", Balance: 1000, Customer: &model.Customer{ID: id}},
		},
	}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
