package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/n9te9/go-graphql-federation-gateway/_example/fintech/accounts/graph/model"
)

// Account is the resolver for the account field.
func (r *queryResolver) Account(ctx context.Context, iban string) (*model.Account, error) {
	return &model.Account{
		Iban:     iban,
		ID:       "acc_" + iban,
		Balance:  1000,
		Customer: &model.Customer{ID: "1"},
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
