// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Customer struct {
	ID          string `json:"id"`
	Tier        string `json:"tier"`
	GdprConsent bool   `json:"gdprConsent"`
}

func (Customer) IsEntity() {}

type Query struct {
}
