package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/n9te9/go-graphql-federation-gateway/_example/saas/billing/graph/model"
)

// FindBillingInfoByID is the resolver for the findBillingInfoByID field.
func (r *entityResolver) FindBillingInfoByID(ctx context.Context, id string) (*model.BillingInfo, error) {
	// Return test data
	if id == "bill1" {
		return &model.BillingInfo{ID: id, Plan: "Enterprise"}, nil
	}
	return &model.BillingInfo{ID: id, Plan: "Free"}, nil
}

// FindOrganizationByID is the resolver for the findOrganizationByID field.
func (r *entityResolver) FindOrganizationByID(ctx context.Context, id string) (*model.Organization, error) {
	// Return Organization with billing info
	billingInfo := &model.BillingInfo{ID: "bill1", Plan: "Enterprise"}
	if id == "org1" {
		return &model.Organization{ID: id, Billing: billingInfo}, nil
	}
	return &model.Organization{ID: id, Billing: nil}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
