// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Account struct {
	Iban         string         `json:"iban"`
	Balance      int            `json:"balance"`
	Transactions []*Transaction `json:"transactions"`
	RiskScore    float64        `json:"riskScore"`
}

func (Account) IsEntity() {}

type Query struct {
}

type Transaction struct {
	ID     string `json:"id"`
	Amount int    `json:"amount"`
}

func (Transaction) IsEntity() {}
