// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Booking struct {
	ID     string  `json:"id"`
	Flight *Flight `json:"flight"`
}

func (Booking) IsEntity() {}

type Flight struct {
	Number        string     `json:"number"`
	DepartureDate string     `json:"departureDate"`
	Price         float64    `json:"price"`
	Bookings      []*Booking `json:"bookings"`
	TotalCost     float64    `json:"totalCost"`
}

func (Flight) IsEntity() {}

type Query struct {
}
