// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
	GetID() string
}

type Mutation struct {
}

type Product struct {
	ID              string           `json:"id"`
	Name            string           `json:"name"`
	Price           int              `json:"price"`
	Weight          float64          `json:"weight"`
	ShippingAddress *ShippingAddress `json:"shippingAddress"`
	InternalCode    string           `json:"internalCode"`
}

func (Product) IsNode()            {}
func (this Product) GetID() string { return this.ID }

func (Product) IsEntity() {}

type Query struct {
}

type ShippingAddress struct {
	ZipCode string `json:"zipCode"`
	Country string `json:"country"`
}
