// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Product struct {
	Upc              string `json:"upc"`
	Weight           *int32 `json:"weight,omitempty"`
	Price            *int32 `json:"price,omitempty"`
	ShippingEstimate *int32 `json:"shippingEstimate,omitempty"`
}

func (Product) IsEntity() {}

type Query struct {
}
