// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type TravelOption interface {
	IsTravelOption()
}

type Flight struct {
	Number        string `json:"number"`
	DepartureDate string `json:"departureDate"`
}

func (Flight) IsTravelOption() {}

func (Flight) IsEntity() {}

type Hotel struct {
	ID string `json:"id"`
}

func (Hotel) IsTravelOption() {}

func (Hotel) IsEntity() {}

type Query struct {
}
