// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Product struct {
	Upc     string    `json:"upc"`
	Reviews []*Review `json:"reviews,omitempty"`
}

func (Product) IsEntity() {}

type Query struct {
}

type Review struct {
	Body    *string  `json:"body,omitempty"`
	Author  *User    `json:"author,omitempty"`
	Product *Product `json:"product,omitempty"`
}

type User struct {
	ID      string    `json:"id"`
	Reviews []*Review `json:"reviews,omitempty"`
}

func (User) IsEntity() {}
