// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewProduct struct {
	Upc string `json:"upc"`
}

type NewReview struct {
	Body    *string     `json:"body,omitempty"`
	Author  *NewUser    `json:"author,omitempty"`
	Product *NewProduct `json:"product,omitempty"`
}

type NewUser struct {
	ID string `json:"id"`
}

type Product struct {
	Upc     string    `json:"upc"`
	Reviews []*Review `json:"reviews,omitempty"`
}

func (Product) IsEntity() {}

type Query struct {
}

type Review struct {
	ID      string   `json:"id"`
	Body    *string  `json:"body,omitempty"`
	Author  *User    `json:"author,omitempty"`
	Product *Product `json:"product,omitempty"`
}

type User struct {
	ID      string    `json:"id"`
	Reviews []*Review `json:"reviews,omitempty"`
}

func (User) IsEntity() {}
