extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.0",
        import: ["@key", "@external", "@interfaceObject", "@provides"])

interface Node {
  id: ID!
}

type User @key(fields: "id") {
  id: ID! @external
  username: String! @external
}

type Review implements Node {
  id: ID!
  body: String!
  authorName: String!
  author: User @provides(fields: "username")
  product: Product @provides(fields: "name price")
}

type Product @key(fields: "id") {
  id: ID! @external
  reviews: [Review]
}
