package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/n9te9/go-graphql-federation-gateway/_example/saas/resources/graph/model"
)

// Resources is the resolver for the resources field.
func (r *queryResolver) Resources(ctx context.Context) ([]*model.Resource, error) {
	return []*model.Resource{
		{
			ID:        "res1",
			Name:      "Database Cluster",
			Owner:     "org1",
			CreatedAt: "2024-01-15T10:00:00Z",
		},
		{
			ID:        "res2",
			Name:      "API Gateway",
			Owner:     "org1",
			CreatedAt: "2024-02-20T14:30:00Z",
		},
	}, nil
}

// Resource is the resolver for the resource field.
func (r *queryResolver) Resource(ctx context.Context, id string) (*model.Resource, error) {
	// Return test data
	if id == "res1" {
		return &model.Resource{
			ID:        id,
			Name:      "Database Cluster",
			Owner:     "org1",
			CreatedAt: "2024-01-15T10:00:00Z",
		}, nil
	}
	return &model.Resource{
		ID:        id,
		Name:      "Resource " + id,
		Owner:     "org1",
		CreatedAt: "2024-01-01T00:00:00Z",
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
